In [1]:
%cd ..
%load_ext autoreload
%autoreload 2
# %load_ext nb_black
# notebook setup

from pathlib import Path
import sys

sys.path.insert(0, Path().absolute().parent.as_posix())

/Users/ruizhechao/Documents/NNforHJB

In [2]:
import numpy as np
import torch
import random

In [3]:
# load the data


path = 'rawdata/raw_data/data/VDP_beta_0.1_grid_30x30.npy'
data = np.load(path)
len(data)

900

In [4]:
# prepare the data
# data is a structured numpy array with fields: 'x', 'dv', 'v'
# convert to the dict format expected by model._prepare_data

data_dict = {
    "x": np.asarray(data["x"], dtype=np.float64),    # shape (N, 2)
    "v": np.asarray(data["v"], dtype=np.float64),    # shape (N,)
    "dv": np.asarray(data["dv"], dtype=np.float64),  # shape (N, 2)
}

## Test effect of different gamma with increased neurons added

specify the hyperparameters

In [ ]:
#
seed = 42

gammas = [0, 1e-2, 1e-1, 1, 10] 
alpha = 1e-5
power = 1.0
activation = torch.relu
use_sphere = True

num_iterations = 10
num_insertions = 50
pruning_threshold = 1e-5

load the random seed

In [6]:
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)  # if you ever use GPU
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

#### L2 loss

In [7]:
from src.PDPA_v2 import PDPA_v2

results_l2 = []

for gamma in gammas:
    pdpa = PDPA_v2(
        data=data_dict,
        alpha=alpha,
        gamma=gamma,
        power=power,
        activation=activation,
        use_sphere=use_sphere,
        loss_weights="l2",
        verbose=True,
    )

    result = pdpa.retrain(
        num_iterations=num_iterations,
        num_insertion=num_insertions,
        threshold=pruning_threshold,
        verbose=True,
    )
    results_l2.append(result)

2026-04-13 15:22:50.160 | INFO     | src.model:__init__:72 - Model initialized
2026-04-13 15:22:50.160 | INFO     | src.model:_prepare_data:107 - Training set: 899 samples, Validation set: 1 samples
2026-04-13 15:22:50.161 | INFO     | src.PDPA_v2:retrain:714 - Initialization
2026-04-13 15:22:51.537 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 2, accepted 2 (capped <=15, alpha=1e-05)
2026-04-13 15:22:51.538 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.53e+01, what=7.90e+01, tau=1.9353e-01, |W_outer| range=[2.88e-09, 1.94e-01]
2026-04-13 15:22:51.538 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:51.539 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:51.543 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.179905, Val Loss = 20.864705
2026-04-13 15:22:51.545 | INFO     | src.model:train:385 - Epoch 2: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.547 | INFO     | src.model:train:385 - Epoch 4: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.550 | INFO     | src.model:train:385 - Epoch 6: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.551 | INFO     | src.model:train:385 - Epoch 8: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.553 | INFO     | src.model:train:385 - Epoch 10: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.555 | INFO     | src.model:train:385 - Epoch 12: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.557 | INFO     | src.model:train:385 - Epoch 14: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.559 | INFO     | src.model:train:385 - Epoch 16: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.561 | INFO     | src.model:train:385 - Epoch 18: Train Loss = 1.039647, Val Loss = 4.781287
2026-04-13 15:22:51.562 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 2
2026-04-13 15:22:51.564 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   1, supp: 2->2, train: 1.04e+00, val: 4.78e+00, L2: 3.99e-01, H1: 4.40e-01
2026-04-13 15:22:52.442 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 5, accepted 5 (capped <=15, alpha=1e-05)
2026-04-13 15:22:52.443 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-7.87e+00, what=7.99e+01, tau=9.8519e-02, |W_outer| range=[1.47e-09, 9.85e-02]
2026-04-13 15:22:52.444 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:52.444 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:52.526 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:52.526 | DEBUG    | src.ssn:step:243 - loss=6.518104e-01, loss_new=0.9082575351204092, theta=1.00e-12
2026-04-13 15:22:52.527 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:22:52.527 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.651810, Val Loss = 4.781290
2026-04-13 15:22:52.607 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:52.607 | DEBUG    | src.ssn:step:243 - loss=6.518104e-01, loss_new=0.9082575351204092, theta=1.00e-12
2026-04-13 15:22:52.608 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:22:52.686 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:52.686 | DEBUG    | src.ssn:step:243 - loss=6.518104e-01, loss_new=0.9082575351204092, theta=1.00e-12
2026-04-13 15:22:52.687 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:22:52.687 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:22:52.688 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:22:52.689 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   2, supp: 7->7, train: 6.52e-01, val: 4.78e+00, L2: 3.99e-01, H1: 4.40e-01
2026-04-13 15:22:52.690 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:22:53.561 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 5, accepted 5 (capped <=15, alpha=1e-05)
2026-04-13 15:22:53.562 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-7.56e+00, what=7.78e+01, tau=9.7190e-02, |W_outer| range=[1.45e-09, 9.72e-02]
2026-04-13 15:22:53.563 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:53.563 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:53.649 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:53.650 | DEBUG    | src.ssn:step:243 - loss=2.843775e-01, loss_new=3.9055964958525036, theta=1.00e-12
2026-04-13 15:22:53.651 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:22:53.651 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.284377, Val Loss = 4.886744
2026-04-13 15:22:53.748 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:53.748 | DEBUG    | src.ssn:step:243 - loss=2.843775e-01, loss_new=3.9055964958525036, theta=1.00e-12
2026-04-13 15:22:53.749 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:22:53.842 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:53.842 | DEBUG    | src.ssn:step:243 - loss=2.843775e-01, loss_new=3.9055964958525036, theta=1.00e-12
2026-04-13 15:22:53.843 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:22:53.844 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:22:53.844 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:22:53.845 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 2 duplicates, removed 0 zeros, kept 10/12
2026-04-13 15:22:53.846 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   3, supp: 12->10, train: 2.84e-01, val: 4.89e+00, L2: 4.04e-01, H1: 4.33e-01
2026-04-13 15:22:53.846 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:22:54.889 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 6, accepted 5 (capped <=15, alpha=1e-05)
2026-04-13 15:22:54.890 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.52e+00, what=7.39e+01, tau=2.0556e-02, |W_outer| range=[3.06e-10, 2.06e-02]
2026-04-13 15:22:54.891 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:54.891 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:54.980 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:54.980 | DEBUG    | src.ssn:step:243 - loss=2.687790e-01, loss_new=12.172483901159948, theta=1.00e-12
2026-04-13 15:22:54.981 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:22:54.981 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.268779, Val Loss = 4.886694
2026-04-13 15:22:55.070 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:55.071 | DEBUG    | src.ssn:step:243 - loss=2.687790e-01, loss_new=12.172483901159948, theta=1.00e-12
2026-04-13 15:22:55.072 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:22:55.165 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:55.165 | DEBUG    | src.ssn:step:243 - loss=2.687790e-01, loss_new=12.172483901159948, theta=1.00e-12
2026-04-13 15:22:55.166 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:22:55.166 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:22:55.166 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:22:55.167 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 2 duplicates, removed 0 zeros, kept 13/15
2026-04-13 15:22:55.168 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   4, supp: 15->13, train: 2.69e-01, val: 4.89e+00, L2: 4.04e-01, H1: 4.33e-01
2026-04-13 15:22:55.169 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:22:56.210 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 9, accepted 6 (capped <=15, alpha=1e-05)
2026-04-13 15:22:56.211 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.51e+00, what=7.08e+01, tau=2.1280e-02, |W_outer| range=[3.17e-10, 2.13e-02]
2026-04-13 15:22:56.211 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:56.212 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:56.309 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:56.309 | DEBUG    | src.ssn:step:243 - loss=2.527385e-01, loss_new=12.481338587259575, theta=1.00e-12
2026-04-13 15:22:56.310 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:22:56.310 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.252739, Val Loss = 1.883966
2026-04-13 15:22:56.405 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:56.406 | DEBUG    | src.ssn:step:243 - loss=2.527385e-01, loss_new=12.481338587259575, theta=1.00e-12
2026-04-13 15:22:56.407 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:22:56.503 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:56.503 | DEBUG    | src.ssn:step:243 - loss=2.527385e-01, loss_new=12.481338587259575, theta=1.00e-12
2026-04-13 15:22:56.504 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:22:56.504 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:22:56.504 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:22:56.506 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 16/19
2026-04-13 15:22:56.507 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   5, supp: 19->16, train: 2.53e-01, val: 1.88e+00, L2: 2.51e-01, H1: 3.85e-01
2026-04-13 15:22:56.507 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:22:57.605 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 8, accepted 7 (capped <=15, alpha=1e-05)
2026-04-13 15:22:57.606 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.10e+00, what=4.77e+01, tau=2.3025e-02, |W_outer| range=[3.43e-10, 2.30e-02]
2026-04-13 15:22:57.607 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:57.607 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:57.711 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:57.711 | DEBUG    | src.ssn:step:243 - loss=2.401012e-01, loss_new=11.716551526687011, theta=1.00e-12
2026-04-13 15:22:57.712 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:22:57.713 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.240101, Val Loss = 1.884008
2026-04-13 15:22:57.817 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:57.818 | DEBUG    | src.ssn:step:243 - loss=2.401012e-01, loss_new=11.716551526687011, theta=1.00e-12
2026-04-13 15:22:57.819 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:22:57.921 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:57.921 | DEBUG    | src.ssn:step:243 - loss=2.401012e-01, loss_new=11.716551526687011, theta=1.00e-12
2026-04-13 15:22:57.923 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:22:57.923 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:22:57.923 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:22:57.925 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 4 duplicates, removed 0 zeros, kept 19/23
2026-04-13 15:22:57.926 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   6, supp: 23->19, train: 2.40e-01, val: 1.88e+00, L2: 2.51e-01, H1: 3.85e-01
2026-04-13 15:22:57.926 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:22:59.131 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 8, accepted 7 (capped <=15, alpha=1e-05)
2026-04-13 15:22:59.132 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.02e+00, what=4.63e+01, tau=2.1987e-02, |W_outer| range=[3.28e-10, 2.20e-02]
2026-04-13 15:22:59.132 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:22:59.133 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:22:59.236 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:59.236 | DEBUG    | src.ssn:step:243 - loss=2.289401e-01, loss_new=27.867669092771372, theta=1.00e-12
2026-04-13 15:22:59.237 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:22:59.237 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.228940, Val Loss = 3.099342
2026-04-13 15:22:59.340 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:59.340 | DEBUG    | src.ssn:step:243 - loss=2.289401e-01, loss_new=27.867669092771372, theta=1.00e-12
2026-04-13 15:22:59.341 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:22:59.442 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:22:59.442 | DEBUG    | src.ssn:step:243 - loss=2.289401e-01, loss_new=27.867669092771372, theta=1.00e-12
2026-04-13 15:22:59.443 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:22:59.443 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:22:59.443 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:22:59.445 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 23/26
2026-04-13 15:22:59.446 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   7, supp: 26->23, train: 2.29e-01, val: 3.10e+00, L2: 3.21e-01, H1: 3.78e-01
2026-04-13 15:22:59.446 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:23:00.691 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 8, accepted 8 (capped <=15, alpha=1e-05)
2026-04-13 15:23:00.692 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-9.24e-01, what=7.12e+01, tau=1.2980e-02, |W_outer| range=[1.93e-10, 1.30e-02]
2026-04-13 15:23:00.693 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:23:00.693 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:23:00.801 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:23:00.801 | DEBUG    | src.ssn:step:243 - loss=2.229470e-01, loss_new=67.88363591656457, theta=1.00e-12
2026-04-13 15:23:00.802 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:23:00.802 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.222947, Val Loss = 3.093860
2026-04-13 15:23:00.910 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:23:00.910 | DEBUG    | src.ssn:step:243 - loss=2.229470e-01, loss_new=67.88363591656457, theta=1.00e-12
2026-04-13 15:23:00.911 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:23:01.053 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:23:01.054 | DEBUG    | src.ssn:step:243 - loss=2.229470e-01, loss_new=67.88363591656457, theta=1.00e-12
2026-04-13 15:23:01.055 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:23:01.055 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:23:01.055 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:23:01.057 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 4 duplicates, removed 0 zeros, kept 27/31
2026-04-13 15:23:01.058 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   8, supp: 31->27, train: 2.23e-01, val: 3.10e+00, L2: 3.21e-01, H1: 3.78e-01
2026-04-13 15:23:01.058 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:23:02.253 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 8, accepted 7 (capped <=15, alpha=1e-05)
2026-04-13 15:23:02.254 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-8.76e-01, what=6.98e+01, tau=1.2542e-02, |W_outer| range=[1.87e-10, 1.25e-02]
2026-04-13 15:23:02.254 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:23:02.255 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:23:02.370 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:23:02.370 | DEBUG    | src.ssn:step:243 - loss=2.174461e-01, loss_new=77.19146233016417, theta=1.00e-12
2026-04-13 15:23:02.371 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:23:02.371 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 0.217446, Val Loss = 3.095315
2026-04-13 15:23:02.487 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:23:02.488 | DEBUG    | src.ssn:step:243 - loss=2.174461e-01, loss_new=77.19146233016417, theta=1.00e-12
2026-04-13 15:23:02.489 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:23:02.602 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:23:02.602 | DEBUG    | src.ssn:step:243 - loss=2.174461e-01, loss_new=77.19146233016417, theta=1.00e-12
2026-04-13 15:23:02.603 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:23:02.604 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:23:02.604 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0

In [8]:
import pickle

with open("models/experiment_9.pkl", "wb") as f:
    pickle.dump(results_l2, f)

print([r["best_iteration"] for r in results_l2])
print([r["final_neurons"] for r in results_l2])

[9, 9, 9, 9, 9]
[40, 39, 35, 39, 37]

#### H1 loss

In [9]:
from src.PDPA_v2 import PDPA_v2

results_h1 = []

for gamma in gammas:
    pdpa = PDPA_v2(
        data=data_dict,
        alpha=alpha,
        gamma=gamma,
        power=power,
        activation=activation,
        use_sphere=use_sphere,
        loss_weights="h1",
        verbose=True,
    )

    result = pdpa.retrain(
        num_iterations=num_iterations,
        num_insertion=num_insertions,
        threshold=pruning_threshold,
        decorrelation=False,
        verbose=True,
    )
    results_h1.append(result)

2026-04-13 15:24:01.454 | INFO     | src.model:__init__:72 - Model initialized
2026-04-13 15:24:01.456 | INFO     | src.model:_prepare_data:107 - Training set: 899 samples, Validation set: 1 samples
2026-04-13 15:24:01.456 | INFO     | src.PDPA_v2:retrain:714 - Initialization
2026-04-13 15:24:02.184 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 3, accepted 2 (capped <=15, alpha=1e-05)
2026-04-13 15:24:02.185 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-3.49e+01, what=1.15e+02, tau=3.0263e-01, |W_outer| range=[4.51e-09, 3.03e-01]
2026-04-13 15:24:02.185 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:02.185 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:02.190 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 2.084868, Val Loss = 22.387827
2026-04-13 15:24:02.192 | INFO     | src.model:train:385 - Epoch 2: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.194 | INFO     | src.model:train:385 - Epoch 4: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.196 | INFO     | src.model:train:385 - Epoch 6: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.198 | INFO     | src.model:train:385 - Epoch 8: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.200 | INFO     | src.model:train:385 - Epoch 10: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.202 | INFO     | src.model:train:385 - Epoch 12: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.203 | INFO     | src.model:train:385 - Epoch 14: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.205 | INFO     | src.model:train:385 - Epoch 16: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.207 | INFO     | src.model:train:385 - Epoch 18: Train Loss = 2.033176, Val Loss = 14.390328
2026-04-13 15:24:02.209 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 2
2026-04-13 15:24:02.210 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   1, supp: 2->2, train: 2.03e+00, val: 1.44e+01, L2: 6.61e-01, H1: 4.40e-01
2026-04-13 15:24:03.053 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 5, accepted 4 (capped <=15, alpha=1e-05)
2026-04-13 15:24:03.054 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.07e+01, what=1.42e+02, tau=7.5349e-02, |W_outer| range=[1.12e-09, 7.53e-02]
2026-04-13 15:24:03.054 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:03.054 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:03.132 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:03.132 | DEBUG    | src.ssn:step:243 - loss=1.631181e+00, loss_new=3.481461931102722, theta=1.00e-12
2026-04-13 15:24:03.133 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:03.133 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.631181, Val Loss = 14.390331
2026-04-13 15:24:03.210 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:03.211 | DEBUG    | src.ssn:step:243 - loss=1.631181e+00, loss_new=3.481461931102722, theta=1.00e-12
2026-04-13 15:24:03.211 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:03.289 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:03.289 | DEBUG    | src.ssn:step:243 - loss=1.631181e+00, loss_new=3.481461931102722, theta=1.00e-12
2026-04-13 15:24:03.290 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:03.290 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:03.291 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:03.292 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   2, supp: 6->6, train: 1.63e+00, val: 1.44e+01, L2: 6.61e-01, H1: 4.40e-01
2026-04-13 15:24:03.292 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:04.327 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 6, accepted 6 (capped <=15, alpha=1e-05)
2026-04-13 15:24:04.328 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-9.71e+00, what=1.39e+02, tau=7.0062e-02, |W_outer| range=[1.04e-09, 7.01e-02]
2026-04-13 15:24:04.329 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:04.329 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:04.416 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:04.416 | DEBUG    | src.ssn:step:243 - loss=1.291177e+00, loss_new=12.803467605943458, theta=1.00e-12
2026-04-13 15:24:04.417 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:04.417 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.291177, Val Loss = 14.396314
2026-04-13 15:24:04.503 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:04.504 | DEBUG    | src.ssn:step:243 - loss=1.291177e+00, loss_new=12.803467605943458, theta=1.00e-12
2026-04-13 15:24:04.505 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:04.590 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:04.590 | DEBUG    | src.ssn:step:243 - loss=1.291177e+00, loss_new=12.803467605943458, theta=1.00e-12
2026-04-13 15:24:04.591 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:04.592 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:04.592 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:04.593 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 2 duplicates, removed 0 zeros, kept 10/12
2026-04-13 15:24:04.594 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   3, supp: 12->10, train: 1.29e+00, val: 1.44e+01, L2: 6.63e-01, H1: 4.40e-01
2026-04-13 15:24:04.594 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:05.482 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 6, accepted 6 (capped <=15, alpha=1e-05)
2026-04-13 15:24:05.483 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-4.52e+00, what=1.46e+02, tau=3.0995e-02, |W_outer| range=[4.62e-10, 3.10e-02]
2026-04-13 15:24:05.483 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:05.484 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:05.564 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:05.564 | DEBUG    | src.ssn:step:243 - loss=1.221154e+00, loss_new=16.071791054143244, theta=1.00e-12
2026-04-13 15:24:05.565 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:05.565 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.221154, Val Loss = 14.396320
2026-04-13 15:24:05.646 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:05.646 | DEBUG    | src.ssn:step:243 - loss=1.221154e+00, loss_new=16.071791054143244, theta=1.00e-12
2026-04-13 15:24:05.647 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:05.727 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:05.727 | DEBUG    | src.ssn:step:243 - loss=1.221154e+00, loss_new=16.071791054143244, theta=1.00e-12
2026-04-13 15:24:05.728 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:05.728 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:05.728 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:05.730 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 13/16
2026-04-13 15:24:05.730 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   4, supp: 16->13, train: 1.22e+00, val: 1.44e+01, L2: 6.63e-01, H1: 4.40e-01
2026-04-13 15:24:05.731 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:06.651 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 7, accepted 7 (capped <=15, alpha=1e-05)
2026-04-13 15:24:06.652 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-4.06e+00, what=1.39e+02, tau=2.9253e-02, |W_outer| range=[4.36e-10, 2.93e-02]
2026-04-13 15:24:06.653 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:06.653 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:06.748 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:06.748 | DEBUG    | src.ssn:step:243 - loss=1.161790e+00, loss_new=11.647058916136432, theta=1.00e-12
2026-04-13 15:24:06.749 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:06.749 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.161790, Val Loss = 6.737510
2026-04-13 15:24:06.844 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:06.844 | DEBUG    | src.ssn:step:243 - loss=1.161790e+00, loss_new=11.647058916136432, theta=1.00e-12
2026-04-13 15:24:06.845 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:06.940 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:06.940 | DEBUG    | src.ssn:step:243 - loss=1.161790e+00, loss_new=11.647058916136432, theta=1.00e-12
2026-04-13 15:24:06.941 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:06.941 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:06.941 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:06.943 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 17/20
2026-04-13 15:24:06.944 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   5, supp: 20->17, train: 1.16e+00, val: 6.74e+00, L2: 4.42e-01, H1: 3.01e-01
2026-04-13 15:24:06.944 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:07.546 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 8, accepted 8 (capped <=15, alpha=1e-05)
2026-04-13 15:24:07.547 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.69e+00, what=8.55e+01, tau=1.9729e-02, |W_outer| range=[2.94e-10, 1.97e-02]
2026-04-13 15:24:07.547 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:07.547 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:07.649 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:07.650 | DEBUG    | src.ssn:step:243 - loss=1.145156e+00, loss_new=3.526920593089829, theta=1.00e-12
2026-04-13 15:24:07.651 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:07.651 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.145156, Val Loss = 6.737441
2026-04-13 15:24:07.752 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:07.752 | DEBUG    | src.ssn:step:243 - loss=1.145156e+00, loss_new=3.526920593089829, theta=1.00e-12
2026-04-13 15:24:07.753 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:07.855 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:07.855 | DEBUG    | src.ssn:step:243 - loss=1.145156e+00, loss_new=3.526920593089829, theta=1.00e-12
2026-04-13 15:24:07.856 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:07.856 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:07.856 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:07.858 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 22/25
2026-04-13 15:24:07.859 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   6, supp: 25->22, train: 1.15e+00, val: 6.74e+00, L2: 4.42e-01, H1: 3.01e-01
2026-04-13 15:24:07.859 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:08.519 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 7, accepted 7 (capped <=15, alpha=1e-05)
2026-04-13 15:24:08.520 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.42e+00, what=8.11e+01, tau=1.7550e-02, |W_outer| range=[2.62e-10, 1.75e-02]
2026-04-13 15:24:08.521 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:08.521 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:08.628 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:08.628 | DEBUG    | src.ssn:step:243 - loss=1.132712e+00, loss_new=25.003970984314165, theta=1.00e-12
2026-04-13 15:24:08.629 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:08.630 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.132712, Val Loss = 7.421602
2026-04-13 15:24:08.736 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:08.736 | DEBUG    | src.ssn:step:243 - loss=1.132712e+00, loss_new=25.003970984314165, theta=1.00e-12
2026-04-13 15:24:08.737 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:08.843 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:08.844 | DEBUG    | src.ssn:step:243 - loss=1.132712e+00, loss_new=25.003970984314165, theta=1.00e-12
2026-04-13 15:24:08.845 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:08.845 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:08.845 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:08.847 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 26/29
2026-04-13 15:24:08.848 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   7, supp: 29->26, train: 1.13e+00, val: 7.42e+00, L2: 4.78e-01, H1: 3.16e-01
2026-04-13 15:24:08.848 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:09.738 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 9, accepted 9 (capped <=15, alpha=1e-05)
2026-04-13 15:24:09.739 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.39e+00, what=1.40e+02, tau=9.9308e-03, |W_outer| range=[1.48e-10, 9.93e-03]
2026-04-13 15:24:09.740 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:09.740 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:09.858 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:09.858 | DEBUG    | src.ssn:step:243 - loss=1.125796e+00, loss_new=45.31390025532422, theta=1.00e-12
2026-04-13 15:24:09.859 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:09.859 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.125796, Val Loss = 7.420167
2026-04-13 15:24:09.976 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:09.976 | DEBUG    | src.ssn:step:243 - loss=1.125796e+00, loss_new=45.31390025532422, theta=1.00e-12
2026-04-13 15:24:09.977 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:10.096 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:10.096 | DEBUG    | src.ssn:step:243 - loss=1.125796e+00, loss_new=45.31390025532422, theta=1.00e-12
2026-04-13 15:24:10.097 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:10.097 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:10.097 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0
2026-04-13 15:24:10.100 | INFO     | src.PDPA_v2:prune_small_weights:679 - Prune: merged 3 duplicates, removed 0 zeros, kept 32/35
2026-04-13 15:24:10.101 | INFO     | src.PDPA_v2:retrain:788 - PDAP:   8, supp: 35->32, train: 1.13e+00, val: 7.42e+00, L2: 4.78e-01, H1: 3.16e-01
2026-04-13 15:24:10.101 | INFO     | src.PDPA_v2:retrain:796 - SSN made no progress this round
2026-04-13 15:24:11.111 | INFO     | src.PDPA_v2:insertion:348 - insertion: tried 50, after merge 9, accepted 8 (capped <=15, alpha=1e-05)
2026-04-13 15:24:11.112 | INFO     | src.PDPA_v2:_coordinate_descent_init:483 - Coord. descent: phat=-1.16e+00, what=1.36e+02, tau=8.4963e-03, |W_outer| range=[1.27e-10, 8.50e-03]
2026-04-13 15:24:11.113 | INFO     | src.model:_setup_optimizer:186 - Using SSN optimizer with alpha=1e-05, gamma=0, th=0.5, lr =1.0
2026-04-13 15:24:11.113 | INFO     | src.model:train:299 - Starting network training session
2026-04-13 15:24:11.262 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:11.263 | DEBUG    | src.ssn:step:243 - loss=1.120874e+00, loss_new=50.097492116303606, theta=1.00e-12
2026-04-13 15:24:11.264 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=1/3, max_ls_iter=500)
2026-04-13 15:24:11.264 | INFO     | src.model:train:385 - Epoch 0: Train Loss = 1.120874, Val Loss = 7.420587
2026-04-13 15:24:11.411 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:11.412 | DEBUG    | src.ssn:step:243 - loss=1.120874e+00, loss_new=50.097492116303606, theta=1.00e-12
2026-04-13 15:24:11.413 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=2/3, max_ls_iter=500)
2026-04-13 15:24:11.560 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:24:11.561 | DEBUG    | src.ssn:step:243 - loss=1.120874e+00, loss_new=50.097492116303606, theta=1.00e-12
2026-04-13 15:24:11.562 | WARNING  | src.model:train:367 - SSN step rejected (consecutive=3/3, max_ls_iter=500)
2026-04-13 15:24:11.562 | WARNING  | src.model:train:376 - Early stopping: SSN line search failed for 3 consecutive epochs. Restoring best model at epoch 0 (val=inf).
2026-04-13 15:24:11.562 | INFO     | src.model:train:395 - Best validation loss: inf at iteration 0

In [ ]:
# import pickle

# with open("models/experiment_10.pkl", "wb") as f:
#     pickle.dump(results_h1, f)

# print([r["best_iteration"] for r in results_h1])
# print([r["best_neurons"] for r in results_h1])

[9, 9, 9, 9, 9]
[38, 38, 37, 37, 37]

In [ ]:
# # Log experiments to MLflow
# from src.mlflow_utils import log_training_run

# for result in results_l2:
#     run_id = log_training_run(result, seed=seed)
#     print(f"Logged: run_id={run_id}")

# for result in results_h1:
#     run_id = log_training_run(result, seed=seed)
#     print(f"Logged: run_id={run_id}")

Logged: run_id=7eb832cf7fe243e580c196e2e6026329
Logged: run_id=bb0fe0a1cdea47949418147d114de3d3
Logged: run_id=fa106020b17a4850b71007249dd6adfa
Logged: run_id=2d552cc4dabd46208bf2d6fff98078df
Logged: run_id=76d95795ae1a4391b9c818efa41b6132
Logged: run_id=62408c57f9ae49958899106cd58817a0
Logged: run_id=7da5019a334f4b82b704090a257c54a4
Logged: run_id=ac15280a4fd544de98db8a4ad1559ea1
Logged: run_id=f569ed41bece4c798de7c6b57066421b
Logged: run_id=dcfe141e8e7e4186952a3fa2a6f7aec5

## Table 1: Effect of Gradient Data (PDPA v2, alpha=1e-5, gamma=1)

In [12]:
import pickle
import pandas as pd
import numpy as np

with open("models/experiment_9.pkl", "rb") as f:
    results_l2_loaded = pickle.load(f)
with open("models/experiment_10.pkl", "rb") as f:
    results_h1_loaded = pickle.load(f)

def extract_table1_row(result):
    bi = result['best_iteration']
    return {
        'Err_L2': result['err_l2_train'][bi],
        'Err_H1': result['err_h1_train'][bi],
        'N': result['best_neurons'],
        'Err_L2_val': result['err_l2_val'][bi],
        'Err_H1_val': result['err_h1_val'][bi],
    }

# gammas = [0, 1e-2, 1e-1, 1, 10], gamma=1 is index 3
gamma_idx = 3
row_l2 = extract_table1_row(results_l2_loaded[gamma_idx])
row_h1 = extract_table1_row(results_h1_loaded[gamma_idx])

# Training Errors
train_df = pd.DataFrame(
    [[f"{row_l2['Err_L2']:.2e}", f"{row_l2['Err_H1']:.2e}", row_l2['N']],
     [f"{row_h1['Err_L2']:.2e}", f"{row_h1['Err_H1']:.2e}", row_h1['N']]],
    index=["L2 loss (no gradient)", "H1 loss (with gradient)"],
    columns=["Err_L2", "Err_H1", "N (neurons)"]
)
print("Training Errors (alpha=1e-5, gamma=1)")
display(train_df)

# Validation Errors
val_df = pd.DataFrame(
    [[f"{row_l2['Err_L2_val']:.2e}", f"{row_l2['Err_H1_val']:.2e}", row_l2['N']],
     [f"{row_h1['Err_L2_val']:.2e}", f"{row_h1['Err_H1_val']:.2e}", row_h1['N']]],
    index=["L2 loss (no gradient)", "H1 loss (with gradient)"],
    columns=["Err_L2", "Err_H1", "N (neurons)"]
)
print("\nValidation Errors (alpha=1e-5, gamma=1)")
display(val_df)

Training Errors (alpha=1e-5, gamma=1)

                           Err_L2    Err_H1  N (neurons)
L2 loss (no gradient)    2.31e-01  4.47e-01           31
H1 loss (with gradient)  3.36e-01  2.98e-01           37

Validation Errors (alpha=1e-5, gamma=1)

                           Err_L2    Err_H1  N (neurons)
L2 loss (no gradient)    3.21e-01  3.78e-01           31
H1 loss (with gradient)  4.78e-01  3.16e-01           37

## Table 2: Effect of Gamma (PDPA v2, alpha=1e-5, L2 loss)

In [13]:
rows = []
for r in results_l2_loaded:
    bi = r['best_iteration']
    rows.append({
        'gamma': r['gamma'],
        'N': r['best_neurons'],
        '||N-f||': f"{r['err_l2_train'][bi]:.2e}",
    })

gamma_df = pd.DataFrame(rows).set_index('gamma')
display(gamma_df)

        N   ||N-f||
gamma
0.00   33  2.30e-01
0.01   31  2.31e-01
0.10   30  2.30e-01
1.00   31  2.31e-01
10.00  31  2.30e-01

## Table 3: Effect of Alpha (PDPA v2, L2 loss)

Sweep alpha in [1e-2, 1e-3, 1e-4, 1e-5] for gamma=0 and gamma=5.

In [14]:
from src.PDPA_v2 import PDPA_v2

alphas = [1e-2, 1e-3, 1e-4, 1e-5]
gammas_alpha = [0, 5]

results_alpha_v2 = {}
for a in alphas:
    for g in gammas_alpha:
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

        pdpa = PDPA_v2(
            data=data_dict, alpha=a, gamma=g,
            power=power, activation=activation,
            use_sphere=use_sphere, loss_weights="l2", verbose=False,
        )
        result = pdpa.retrain(
            num_iterations=num_iterations, num_insertion=num_insertions,
            threshold=pruning_threshold, verbose=False,
        )
        results_alpha_v2[(a, g)] = result
        bi = result['best_iteration']
        print(f"alpha={a:.0e}, gamma={g}: N={result['best_neurons']}, err_l2={result['err_l2_train'][bi]:.2e}")

with open("models/experiment_13.pkl", "wb") as f:
    pickle.dump(results_alpha_v2, f)

2026-04-13 15:25:08.046 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:08.046 | DEBUG    | src.ssn:step:243 - loss=2.497370e+00, loss_new=320704.77793826524, theta=1.00e-12
2026-04-13 15:25:08.106 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:08.107 | DEBUG    | src.ssn:step:243 - loss=2.497370e+00, loss_new=320704.77793826524, theta=1.00e-12
2026-04-13 15:25:08.169 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:08.169 | DEBUG    | src.ssn:step:243 - loss=2.497370e+00, loss_new=320704.77793826524, theta=1.00e-12
2026-04-13 15:25:08.845 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:08.845 | DEBUG    | src.ssn:step:243 - loss=1.048569e+00, loss_new=911137.3052574003, theta=1.00e-12
2026-04-13 15:25:08.922 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:08.922 | DEBUG    | src.ssn:step:243 - loss=1.048569e+00, loss_new=911137.3052574003, theta=1.00e-12
2026-04-13 15:25:08.999 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:08.999 | DEBUG    | src.ssn:step:243 - loss=1.048569e+00, loss_new=911137.3052574003, theta=1.00e-12
2026-04-13 15:25:09.967 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:09.967 | DEBUG    | src.ssn:step:243 - loss=6.635923e-01, loss_new=2736339.6604356933, theta=1.00e-12
2026-04-13 15:25:10.042 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:10.042 | DEBUG    | src.ssn:step:243 - loss=6.635923e-01, loss_new=2736339.6604356933, theta=1.00e-12
2026-04-13 15:25:10.116 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:10.117 | DEBUG    | src.ssn:step:243 - loss=6.635923e-01, loss_new=2736339.6604356933, theta=1.00e-12
2026-04-13 15:25:11.025 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:11.025 | DEBUG    | src.ssn:step:243 - loss=2.990847e-01, loss_new=4620678.433370002, theta=1.00e-12
2026-04-13 15:25:11.111 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:11.112 | DEBUG    | src.ssn:step:243 - loss=2.990847e-01, loss_new=4620678.433370002, theta=1.00e-12
2026-04-13 15:25:11.197 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:11.198 | DEBUG    | src.ssn:step:243 - loss=2.990847e-01, loss_new=4620678.433370002, theta=1.00e-12
2026-04-13 15:25:12.308 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:12.308 | DEBUG    | src.ssn:step:243 - loss=2.851256e-01, loss_new=15257414.112017704, theta=1.00e-12
2026-04-13 15:25:12.395 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:12.396 | DEBUG    | src.ssn:step:243 - loss=2.851256e-01, loss_new=15257414.112017704, theta=1.00e-12
2026-04-13 15:25:12.483 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:12.483 | DEBUG    | src.ssn:step:243 - loss=2.851256e-01, loss_new=15257414.112017704, theta=1.00e-12
2026-04-13 15:25:13.475 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:13.475 | DEBUG    | src.ssn:step:243 - loss=2.707739e-01, loss_new=14623495.646707363, theta=1.00e-12
2026-04-13 15:25:13.570 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:13.570 | DEBUG    | src.ssn:step:243 - loss=2.707739e-01, loss_new=14623495.646707363, theta=1.00e-12
2026-04-13 15:25:13.666 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:13.666 | DEBUG    | src.ssn:step:243 - loss=2.707739e-01, loss_new=14623495.646707363, theta=1.00e-12
2026-04-13 15:25:14.763 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:14.764 | DEBUG    | src.ssn:step:243 - loss=2.598408e-01, loss_new=12909755.591524882, theta=1.00e-12
2026-04-13 15:25:14.862 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:14.862 | DEBUG    | src.ssn:step:243 - loss=2.598408e-01, loss_new=12909755.591524882, theta=1.00e-12
2026-04-13 15:25:14.960 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:14.961 | DEBUG    | src.ssn:step:243 - loss=2.598408e-01, loss_new=12909755.591524882, theta=1.00e-12
2026-04-13 15:25:16.294 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:16.294 | DEBUG    | src.ssn:step:243 - loss=2.503211e-01, loss_new=24535403.38971306, theta=1.00e-12
2026-04-13 15:25:16.395 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:16.395 | DEBUG    | src.ssn:step:243 - loss=2.503211e-01, loss_new=24535403.38971306, theta=1.00e-12
2026-04-13 15:25:16.498 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:16.499 | DEBUG    | src.ssn:step:243 - loss=2.503211e-01, loss_new=24535403.38971306, theta=1.00e-12
2026-04-13 15:25:17.981 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:17.982 | DEBUG    | src.ssn:step:243 - loss=2.456726e-01, loss_new=57553401.78563553, theta=1.00e-12
2026-04-13 15:25:18.083 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:18.083 | DEBUG    | src.ssn:step:243 - loss=2.456726e-01, loss_new=57553401.78563553, theta=1.00e-12
2026-04-13 15:25:18.184 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:18.184 | DEBUG    | src.ssn:step:243 - loss=2.456726e-01, loss_new=57553401.78563553, theta=1.00e-12
2026-04-13 15:25:19.295 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:19.295 | DEBUG    | src.ssn:step:243 - loss=2.414041e-01, loss_new=67312564.69928066, theta=1.00e-12
2026-04-13 15:25:19.402 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:19.403 | DEBUG    | src.ssn:step:243 - loss=2.414041e-01, loss_new=67312564.69928066, theta=1.00e-12
2026-04-13 15:25:19.509 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:19.509 | DEBUG    | src.ssn:step:243 - loss=2.414041e-01, loss_new=67312564.69928066, theta=1.00e-12

alpha=1e-02, gamma=0: N=27, err_l2=2.34e-01

2026-04-13 15:25:21.652 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:21.652 | DEBUG    | src.ssn:step:243 - loss=2.496015e+00, loss_new=290738.3248765162, theta=1.00e-12
2026-04-13 15:25:21.716 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:21.717 | DEBUG    | src.ssn:step:243 - loss=2.496015e+00, loss_new=290738.3248765162, theta=1.00e-12
2026-04-13 15:25:21.781 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:21.781 | DEBUG    | src.ssn:step:243 - loss=2.496015e+00, loss_new=290738.3248765162, theta=1.00e-12
2026-04-13 15:25:22.450 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:22.450 | DEBUG    | src.ssn:step:243 - loss=1.045746e+00, loss_new=826546.9462765142, theta=1.00e-12
2026-04-13 15:25:22.531 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:22.532 | DEBUG    | src.ssn:step:243 - loss=1.045746e+00, loss_new=826546.9462765142, theta=1.00e-12
2026-04-13 15:25:22.613 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:22.613 | DEBUG    | src.ssn:step:243 - loss=1.045746e+00, loss_new=826546.9462765142, theta=1.00e-12
2026-04-13 15:25:23.578 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:23.578 | DEBUG    | src.ssn:step:243 - loss=6.600711e-01, loss_new=2483875.6556813675, theta=1.00e-12
2026-04-13 15:25:23.658 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:23.658 | DEBUG    | src.ssn:step:243 - loss=6.600711e-01, loss_new=2483875.6556813675, theta=1.00e-12
2026-04-13 15:25:23.737 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:23.737 | DEBUG    | src.ssn:step:243 - loss=6.600711e-01, loss_new=2483875.6556813675, theta=1.00e-12
2026-04-13 15:25:24.648 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:24.649 | DEBUG    | src.ssn:step:243 - loss=2.948018e-01, loss_new=4191817.9945625304, theta=1.00e-12
2026-04-13 15:25:24.740 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:24.740 | DEBUG    | src.ssn:step:243 - loss=2.948018e-01, loss_new=4191817.9945625304, theta=1.00e-12
2026-04-13 15:25:24.831 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:24.831 | DEBUG    | src.ssn:step:243 - loss=2.948018e-01, loss_new=4191817.9945625304, theta=1.00e-12
2026-04-13 15:25:25.954 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:25.955 | DEBUG    | src.ssn:step:243 - loss=2.804845e-01, loss_new=13764219.312937958, theta=1.00e-12
2026-04-13 15:25:26.046 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:26.046 | DEBUG    | src.ssn:step:243 - loss=2.804845e-01, loss_new=13764219.312937958, theta=1.00e-12
2026-04-13 15:25:26.137 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:26.137 | DEBUG    | src.ssn:step:243 - loss=2.804845e-01, loss_new=13764219.312937958, theta=1.00e-12
2026-04-13 15:25:27.172 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:27.172 | DEBUG    | src.ssn:step:243 - loss=2.657521e-01, loss_new=13110300.006454948, theta=1.00e-12
2026-04-13 15:25:27.270 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:27.271 | DEBUG    | src.ssn:step:243 - loss=2.657521e-01, loss_new=13110300.006454948, theta=1.00e-12
2026-04-13 15:25:27.368 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:27.368 | DEBUG    | src.ssn:step:243 - loss=2.657521e-01, loss_new=13110300.006454948, theta=1.00e-12
2026-04-13 15:25:28.512 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:28.512 | DEBUG    | src.ssn:step:243 - loss=2.544873e-01, loss_new=11405932.904136779, theta=1.00e-12
2026-04-13 15:25:28.615 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:28.615 | DEBUG    | src.ssn:step:243 - loss=2.544873e-01, loss_new=11405932.904136779, theta=1.00e-12
2026-04-13 15:25:28.718 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:28.718 | DEBUG    | src.ssn:step:243 - loss=2.544873e-01, loss_new=11405932.904136779, theta=1.00e-12
2026-04-13 15:25:30.075 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:30.076 | DEBUG    | src.ssn:step:243 - loss=2.446513e-01, loss_new=21781525.527988575, theta=1.00e-12
2026-04-13 15:25:30.181 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:30.182 | DEBUG    | src.ssn:step:243 - loss=2.446513e-01, loss_new=21781525.527988575, theta=1.00e-12
2026-04-13 15:25:30.287 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:30.287 | DEBUG    | src.ssn:step:243 - loss=2.446513e-01, loss_new=21781525.527988575, theta=1.00e-12
2026-04-13 15:25:31.779 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:31.779 | DEBUG    | src.ssn:step:243 - loss=2.397523e-01, loss_new=51365411.85720777, theta=1.00e-12
2026-04-13 15:25:31.885 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:31.885 | DEBUG    | src.ssn:step:243 - loss=2.397523e-01, loss_new=51365411.85720777, theta=1.00e-12
2026-04-13 15:25:31.992 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:31.992 | DEBUG    | src.ssn:step:243 - loss=2.397523e-01, loss_new=51365411.85720777, theta=1.00e-12
2026-04-13 15:25:33.080 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:33.081 | DEBUG    | src.ssn:step:243 - loss=2.352701e-01, loss_new=60028248.00664596, theta=1.00e-12
2026-04-13 15:25:33.192 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:33.192 | DEBUG    | src.ssn:step:243 - loss=2.352701e-01, loss_new=60028248.00664596, theta=1.00e-12
2026-04-13 15:25:33.337 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:33.337 | DEBUG    | src.ssn:step:243 - loss=2.352701e-01, loss_new=60028248.00664596, theta=1.00e-12

alpha=1e-02, gamma=5: N=27, err_l2=2.34e-01

2026-04-13 15:25:35.474 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:35.475 | DEBUG    | src.ssn:step:243 - loss=2.493412e+00, loss_new=3084.182224033648, theta=1.00e-12
2026-04-13 15:25:35.533 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:35.534 | DEBUG    | src.ssn:step:243 - loss=2.493412e+00, loss_new=3084.182224033648, theta=1.00e-12
2026-04-13 15:25:35.593 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:35.593 | DEBUG    | src.ssn:step:243 - loss=2.493412e+00, loss_new=3084.182224033648, theta=1.00e-12
2026-04-13 15:25:36.276 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:36.276 | DEBUG    | src.ssn:step:243 - loss=1.040581e+00, loss_new=9044.22337643607, theta=1.00e-12
2026-04-13 15:25:36.352 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:36.352 | DEBUG    | src.ssn:step:243 - loss=1.040581e+00, loss_new=9044.22337643607, theta=1.00e-12
2026-04-13 15:25:36.428 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:36.429 | DEBUG    | src.ssn:step:243 - loss=1.040581e+00, loss_new=9044.22337643607, theta=1.00e-12
2026-04-13 15:25:37.415 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:37.415 | DEBUG    | src.ssn:step:243 - loss=6.529565e-01, loss_new=27282.027647297426, theta=1.00e-12
2026-04-13 15:25:37.490 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:37.490 | DEBUG    | src.ssn:step:243 - loss=6.529565e-01, loss_new=27282.027647297426, theta=1.00e-12
2026-04-13 15:25:37.564 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:37.565 | DEBUG    | src.ssn:step:243 - loss=6.529565e-01, loss_new=27282.027647297426, theta=1.00e-12
2026-04-13 15:25:38.459 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:38.460 | DEBUG    | src.ssn:step:243 - loss=2.858091e-01, loss_new=46136.2614896348, theta=1.00e-12
2026-04-13 15:25:38.545 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:38.546 | DEBUG    | src.ssn:step:243 - loss=2.858091e-01, loss_new=46136.2614896348, theta=1.00e-12
2026-04-13 15:25:38.631 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:38.632 | DEBUG    | src.ssn:step:243 - loss=2.858091e-01, loss_new=46136.2614896348, theta=1.00e-12
2026-04-13 15:25:39.772 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:39.772 | DEBUG    | src.ssn:step:243 - loss=2.703693e-01, loss_new=150077.75317635122, theta=1.00e-12
2026-04-13 15:25:39.859 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:39.859 | DEBUG    | src.ssn:step:243 - loss=2.703693e-01, loss_new=150077.75317635122, theta=1.00e-12
2026-04-13 15:25:39.946 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:39.946 | DEBUG    | src.ssn:step:243 - loss=2.703693e-01, loss_new=150077.75317635122, theta=1.00e-12
2026-04-13 15:25:40.910 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:40.911 | DEBUG    | src.ssn:step:243 - loss=2.545071e-01, loss_new=141316.265160475, theta=1.00e-12
2026-04-13 15:25:41.004 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:41.004 | DEBUG    | src.ssn:step:243 - loss=2.545071e-01, loss_new=141316.265160475, theta=1.00e-12
2026-04-13 15:25:41.097 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:41.098 | DEBUG    | src.ssn:step:243 - loss=2.545071e-01, loss_new=141316.265160475, theta=1.00e-12
2026-04-13 15:25:42.240 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:42.241 | DEBUG    | src.ssn:step:243 - loss=2.420464e-01, loss_new=118920.95604264266, theta=1.00e-12
2026-04-13 15:25:42.339 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:42.340 | DEBUG    | src.ssn:step:243 - loss=2.420464e-01, loss_new=118920.95604264266, theta=1.00e-12
2026-04-13 15:25:42.438 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:42.438 | DEBUG    | src.ssn:step:243 - loss=2.420464e-01, loss_new=118920.95604264266, theta=1.00e-12
2026-04-13 15:25:43.748 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:43.749 | DEBUG    | src.ssn:step:243 - loss=2.310500e-01, loss_new=248047.66957217228, theta=1.00e-12
2026-04-13 15:25:43.838 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:43.838 | DEBUG    | src.ssn:step:243 - loss=2.310500e-01, loss_new=248047.66957217228, theta=1.00e-12
2026-04-13 15:25:43.927 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:43.927 | DEBUG    | src.ssn:step:243 - loss=2.310500e-01, loss_new=248047.66957217228, theta=1.00e-12
2026-04-13 15:25:45.307 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:45.307 | DEBUG    | src.ssn:step:243 - loss=2.251976e-01, loss_new=640189.7512902775, theta=1.00e-12
2026-04-13 15:25:45.411 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:45.412 | DEBUG    | src.ssn:step:243 - loss=2.251976e-01, loss_new=640189.7512902775, theta=1.00e-12
2026-04-13 15:25:45.515 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:45.515 | DEBUG    | src.ssn:step:243 - loss=2.251976e-01, loss_new=640189.7512902775, theta=1.00e-12
2026-04-13 15:25:46.802 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:46.803 | DEBUG    | src.ssn:step:243 - loss=2.198195e-01, loss_new=776524.6647544616, theta=1.00e-12
2026-04-13 15:25:46.909 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:46.910 | DEBUG    | src.ssn:step:243 - loss=2.198195e-01, loss_new=776524.6647544616, theta=1.00e-12
2026-04-13 15:25:47.016 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:47.017 | DEBUG    | src.ssn:step:243 - loss=2.198195e-01, loss_new=776524.6647544616, theta=1.00e-12

alpha=1e-03, gamma=0: N=28, err_l2=2.34e-01

2026-04-13 15:25:48.952 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:48.953 | DEBUG    | src.ssn:step:243 - loss=2.493276e+00, loss_new=3052.821688095802, theta=1.00e-12
2026-04-13 15:25:49.017 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:49.018 | DEBUG    | src.ssn:step:243 - loss=2.493276e+00, loss_new=3052.821688095802, theta=1.00e-12
2026-04-13 15:25:49.082 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:49.082 | DEBUG    | src.ssn:step:243 - loss=2.493276e+00, loss_new=3052.821688095802, theta=1.00e-12
2026-04-13 15:25:49.741 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:49.741 | DEBUG    | src.ssn:step:243 - loss=1.040308e+00, loss_new=8954.264276244874, theta=1.00e-12
2026-04-13 15:25:49.822 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:49.822 | DEBUG    | src.ssn:step:243 - loss=1.040308e+00, loss_new=8954.264276244874, theta=1.00e-12
2026-04-13 15:25:49.903 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:49.904 | DEBUG    | src.ssn:step:243 - loss=1.040308e+00, loss_new=8954.264276244874, theta=1.00e-12
2026-04-13 15:25:50.897 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:50.897 | DEBUG    | src.ssn:step:243 - loss=6.526041e-01, loss_new=27012.56732334659, theta=1.00e-12
2026-04-13 15:25:50.976 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:50.977 | DEBUG    | src.ssn:step:243 - loss=6.526041e-01, loss_new=27012.56732334659, theta=1.00e-12
2026-04-13 15:25:51.056 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:51.056 | DEBUG    | src.ssn:step:243 - loss=6.526041e-01, loss_new=27012.56732334659, theta=1.00e-12
2026-04-13 15:25:51.954 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:51.955 | DEBUG    | src.ssn:step:243 - loss=2.853788e-01, loss_new=45677.414018393756, theta=1.00e-12
2026-04-13 15:25:52.045 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:52.046 | DEBUG    | src.ssn:step:243 - loss=2.853788e-01, loss_new=45677.414018393756, theta=1.00e-12
2026-04-13 15:25:52.136 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:52.137 | DEBUG    | src.ssn:step:243 - loss=2.853788e-01, loss_new=45677.414018393756, theta=1.00e-12
2026-04-13 15:25:53.292 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:53.292 | DEBUG    | src.ssn:step:243 - loss=2.699028e-01, loss_new=148507.16584128927, theta=1.00e-12
2026-04-13 15:25:53.385 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:53.385 | DEBUG    | src.ssn:step:243 - loss=2.699028e-01, loss_new=148507.16584128927, theta=1.00e-12
2026-04-13 15:25:53.476 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:53.477 | DEBUG    | src.ssn:step:243 - loss=2.699028e-01, loss_new=148507.16584128927, theta=1.00e-12
2026-04-13 15:25:54.528 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:54.529 | DEBUG    | src.ssn:step:243 - loss=2.540035e-01, loss_new=139752.17711492247, theta=1.00e-12
2026-04-13 15:25:54.627 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:54.628 | DEBUG    | src.ssn:step:243 - loss=2.540035e-01, loss_new=139752.17711492247, theta=1.00e-12
2026-04-13 15:25:54.725 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:54.726 | DEBUG    | src.ssn:step:243 - loss=2.540035e-01, loss_new=139752.17711492247, theta=1.00e-12
2026-04-13 15:25:55.863 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:55.864 | DEBUG    | src.ssn:step:243 - loss=2.415090e-01, loss_new=117453.6587034188, theta=1.00e-12
2026-04-13 15:25:55.966 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:55.967 | DEBUG    | src.ssn:step:243 - loss=2.415090e-01, loss_new=117453.6587034188, theta=1.00e-12
2026-04-13 15:25:56.070 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:56.070 | DEBUG    | src.ssn:step:243 - loss=2.415090e-01, loss_new=117453.6587034188, theta=1.00e-12
2026-04-13 15:25:57.325 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:57.325 | DEBUG    | src.ssn:step:243 - loss=2.304803e-01, loss_new=245062.20930212786, theta=1.00e-12
2026-04-13 15:25:57.419 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:57.419 | DEBUG    | src.ssn:step:243 - loss=2.304803e-01, loss_new=245062.20930212786, theta=1.00e-12
2026-04-13 15:25:57.518 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:57.518 | DEBUG    | src.ssn:step:243 - loss=2.304803e-01, loss_new=245062.20930212786, theta=1.00e-12
2026-04-13 15:25:58.954 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:58.954 | DEBUG    | src.ssn:step:243 - loss=2.246021e-01, loss_new=632859.7383139242, theta=1.00e-12
2026-04-13 15:25:59.062 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:59.062 | DEBUG    | src.ssn:step:243 - loss=2.246021e-01, loss_new=632859.7383139242, theta=1.00e-12
2026-04-13 15:25:59.169 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:25:59.170 | DEBUG    | src.ssn:step:243 - loss=2.246021e-01, loss_new=632859.7383139242, theta=1.00e-12
2026-04-13 15:26:00.472 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:00.472 | DEBUG    | src.ssn:step:243 - loss=2.192016e-01, loss_new=767712.4653203232, theta=1.00e-12
2026-04-13 15:26:00.584 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:00.584 | DEBUG    | src.ssn:step:243 - loss=2.192016e-01, loss_new=767712.4653203232, theta=1.00e-12
2026-04-13 15:26:00.695 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:00.696 | DEBUG    | src.ssn:step:243 - loss=2.192016e-01, loss_new=767712.4653203232, theta=1.00e-12

alpha=1e-03, gamma=5: N=28, err_l2=2.34e-01

2026-04-13 15:26:02.626 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:02.627 | DEBUG    | src.ssn:step:243 - loss=2.493016e+00, loss_new=20.99572400277876, theta=1.00e-12
2026-04-13 15:26:02.686 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:02.686 | DEBUG    | src.ssn:step:243 - loss=2.493016e+00, loss_new=20.99572400277876, theta=1.00e-12
2026-04-13 15:26:02.745 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:02.745 | DEBUG    | src.ssn:step:243 - loss=2.493016e+00, loss_new=20.99572400277876, theta=1.00e-12
2026-04-13 15:26:03.430 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:03.431 | DEBUG    | src.ssn:step:243 - loss=1.039819e+00, loss_new=84.22912974742644, theta=1.00e-12
2026-04-13 15:26:03.507 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:03.507 | DEBUG    | src.ssn:step:243 - loss=1.039819e+00, loss_new=84.22912974742644, theta=1.00e-12
2026-04-13 15:26:03.583 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:03.583 | DEBUG    | src.ssn:step:243 - loss=1.039819e+00, loss_new=84.22912974742644, theta=1.00e-12
2026-04-13 15:26:04.543 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:04.543 | DEBUG    | src.ssn:step:243 - loss=6.518924e-01, loss_new=260.9530683139577, theta=1.00e-12
2026-04-13 15:26:04.618 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:04.618 | DEBUG    | src.ssn:step:243 - loss=6.518924e-01, loss_new=260.9530683139577, theta=1.00e-12
2026-04-13 15:26:04.692 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:04.692 | DEBUG    | src.ssn:step:243 - loss=6.518924e-01, loss_new=260.9530683139577, theta=1.00e-12
2026-04-13 15:26:05.580 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:05.580 | DEBUG    | src.ssn:step:243 - loss=2.844718e-01, loss_new=454.9913022422838, theta=1.00e-12
2026-04-13 15:26:05.666 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:05.667 | DEBUG    | src.ssn:step:243 - loss=2.844718e-01, loss_new=454.9913022422838, theta=1.00e-12
2026-04-13 15:26:05.752 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:05.752 | DEBUG    | src.ssn:step:243 - loss=2.844718e-01, loss_new=454.9913022422838, theta=1.00e-12
2026-04-13 15:26:06.870 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:06.871 | DEBUG    | src.ssn:step:243 - loss=2.688863e-01, loss_new=1486.6184906283463, theta=1.00e-12
2026-04-13 15:26:06.958 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:06.958 | DEBUG    | src.ssn:step:243 - loss=2.688863e-01, loss_new=1486.6184906283463, theta=1.00e-12
2026-04-13 15:26:07.045 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:07.045 | DEBUG    | src.ssn:step:243 - loss=2.688863e-01, loss_new=1486.6184906283463, theta=1.00e-12
2026-04-13 15:26:08.069 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:08.070 | DEBUG    | src.ssn:step:243 - loss=2.528782e-01, loss_new=1398.9685810072535, theta=1.00e-12
2026-04-13 15:26:08.180 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:08.181 | DEBUG    | src.ssn:step:243 - loss=2.528782e-01, loss_new=1398.9685810072535, theta=1.00e-12
2026-04-13 15:26:08.276 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:08.277 | DEBUG    | src.ssn:step:243 - loss=2.528782e-01, loss_new=1398.9685810072535, theta=1.00e-12
2026-04-13 15:26:09.403 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:09.403 | DEBUG    | src.ssn:step:243 - loss=2.402636e-01, loss_new=1168.1837618665907, theta=1.00e-12
2026-04-13 15:26:09.502 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:09.502 | DEBUG    | src.ssn:step:243 - loss=2.402636e-01, loss_new=1168.1837618665907, theta=1.00e-12
2026-04-13 15:26:09.601 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:09.601 | DEBUG    | src.ssn:step:243 - loss=2.402636e-01, loss_new=1168.1837618665907, theta=1.00e-12
2026-04-13 15:26:10.856 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:10.856 | DEBUG    | src.ssn:step:243 - loss=2.291187e-01, loss_new=2448.110386282591, theta=1.00e-12
2026-04-13 15:26:10.947 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:10.947 | DEBUG    | src.ssn:step:243 - loss=2.291187e-01, loss_new=2448.110386282591, theta=1.00e-12
2026-04-13 15:26:11.037 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:11.037 | DEBUG    | src.ssn:step:243 - loss=2.291187e-01, loss_new=2448.110386282591, theta=1.00e-12
2026-04-13 15:26:12.461 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:12.461 | DEBUG    | src.ssn:step:243 - loss=2.231444e-01, loss_new=6350.437360358025, theta=1.00e-12
2026-04-13 15:26:12.563 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:12.564 | DEBUG    | src.ssn:step:243 - loss=2.231444e-01, loss_new=6350.437360358025, theta=1.00e-12
2026-04-13 15:26:12.666 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:12.667 | DEBUG    | src.ssn:step:243 - loss=2.231444e-01, loss_new=6350.437360358025, theta=1.00e-12
2026-04-13 15:26:13.949 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:13.949 | DEBUG    | src.ssn:step:243 - loss=2.176533e-01, loss_new=7707.635374116327, theta=1.00e-12
2026-04-13 15:26:14.087 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:14.088 | DEBUG    | src.ssn:step:243 - loss=2.176533e-01, loss_new=7707.635374116327, theta=1.00e-12
2026-04-13 15:26:14.194 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:14.194 | DEBUG    | src.ssn:step:243 - loss=2.176533e-01, loss_new=7707.635374116327, theta=1.00e-12

alpha=1e-04, gamma=0: N=28, err_l2=2.34e-01

2026-04-13 15:26:16.116 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:16.116 | DEBUG    | src.ssn:step:243 - loss=2.493002e+00, loss_new=20.970274680506712, theta=1.00e-12
2026-04-13 15:26:16.180 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:16.180 | DEBUG    | src.ssn:step:243 - loss=2.493002e+00, loss_new=20.970274680506712, theta=1.00e-12
2026-04-13 15:26:16.244 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:16.244 | DEBUG    | src.ssn:step:243 - loss=2.493002e+00, loss_new=20.970274680506712, theta=1.00e-12
2026-04-13 15:26:16.960 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:16.960 | DEBUG    | src.ssn:step:243 - loss=1.039773e+00, loss_new=84.1414491939986, theta=1.00e-12
2026-04-13 15:26:17.041 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:17.042 | DEBUG    | src.ssn:step:243 - loss=1.039773e+00, loss_new=84.1414491939986, theta=1.00e-12
2026-04-13 15:26:17.123 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:17.123 | DEBUG    | src.ssn:step:243 - loss=1.039773e+00, loss_new=84.1414491939986, theta=1.00e-12
2026-04-13 15:26:18.090 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:18.090 | DEBUG    | src.ssn:step:243 - loss=6.518573e-01, loss_new=260.689830483223, theta=1.00e-12
2026-04-13 15:26:18.169 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:18.170 | DEBUG    | src.ssn:step:243 - loss=6.518573e-01, loss_new=260.689830483223, theta=1.00e-12
2026-04-13 15:26:18.249 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:18.249 | DEBUG    | src.ssn:step:243 - loss=6.518573e-01, loss_new=260.689830483223, theta=1.00e-12
2026-04-13 15:26:19.145 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:19.145 | DEBUG    | src.ssn:step:243 - loss=2.844349e-01, loss_new=454.54625531317623, theta=1.00e-12
2026-04-13 15:26:19.235 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:19.236 | DEBUG    | src.ssn:step:243 - loss=2.844349e-01, loss_new=454.54625531317623, theta=1.00e-12
2026-04-13 15:26:19.326 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:19.326 | DEBUG    | src.ssn:step:243 - loss=2.844349e-01, loss_new=454.54625531317623, theta=1.00e-12
2026-04-13 15:26:20.462 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:20.463 | DEBUG    | src.ssn:step:243 - loss=2.688425e-01, loss_new=1485.1169430450793, theta=1.00e-12
2026-04-13 15:26:20.559 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:20.559 | DEBUG    | src.ssn:step:243 - loss=2.688425e-01, loss_new=1485.1169430450793, theta=1.00e-12
2026-04-13 15:26:20.651 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:20.651 | DEBUG    | src.ssn:step:243 - loss=2.688425e-01, loss_new=1485.1169430450793, theta=1.00e-12
2026-04-13 15:26:21.655 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:21.655 | DEBUG    | src.ssn:step:243 - loss=2.528276e-01, loss_new=1397.475657502229, theta=1.00e-12
2026-04-13 15:26:21.753 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:21.753 | DEBUG    | src.ssn:step:243 - loss=2.528276e-01, loss_new=1397.475657502229, theta=1.00e-12
2026-04-13 15:26:21.851 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:21.852 | DEBUG    | src.ssn:step:243 - loss=2.528276e-01, loss_new=1397.475657502229, theta=1.00e-12
2026-04-13 15:26:23.005 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:23.006 | DEBUG    | src.ssn:step:243 - loss=2.402095e-01, loss_new=1166.6678236100875, theta=1.00e-12
2026-04-13 15:26:23.109 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:23.109 | DEBUG    | src.ssn:step:243 - loss=2.402095e-01, loss_new=1166.6678236100875, theta=1.00e-12
2026-04-13 15:26:23.212 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:23.212 | DEBUG    | src.ssn:step:243 - loss=2.402095e-01, loss_new=1166.6678236100875, theta=1.00e-12
2026-04-13 15:26:24.476 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:24.477 | DEBUG    | src.ssn:step:243 - loss=2.290608e-01, loss_new=2445.1113970246556, theta=1.00e-12
2026-04-13 15:26:24.571 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:24.572 | DEBUG    | src.ssn:step:243 - loss=2.290608e-01, loss_new=2445.1113970246556, theta=1.00e-12
2026-04-13 15:26:24.667 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:24.667 | DEBUG    | src.ssn:step:243 - loss=2.290608e-01, loss_new=2445.1113970246556, theta=1.00e-12
2026-04-13 15:26:26.102 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:26.103 | DEBUG    | src.ssn:step:243 - loss=2.230840e-01, loss_new=6343.072707204241, theta=1.00e-12
2026-04-13 15:26:26.210 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:26.210 | DEBUG    | src.ssn:step:243 - loss=2.230840e-01, loss_new=6343.072707204241, theta=1.00e-12
2026-04-13 15:26:26.318 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:26.318 | DEBUG    | src.ssn:step:243 - loss=2.230840e-01, loss_new=6343.072707204241, theta=1.00e-12
2026-04-13 15:26:27.602 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:27.602 | DEBUG    | src.ssn:step:243 - loss=2.175906e-01, loss_new=7698.747014007566, theta=1.00e-12
2026-04-13 15:26:27.714 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:27.714 | DEBUG    | src.ssn:step:243 - loss=2.175906e-01, loss_new=7698.747014007566, theta=1.00e-12
2026-04-13 15:26:27.825 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:27.826 | DEBUG    | src.ssn:step:243 - loss=2.175906e-01, loss_new=7698.747014007566, theta=1.00e-12

alpha=1e-04, gamma=5: N=28, err_l2=2.34e-01

2026-04-13 15:26:30.664 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:30.665 | DEBUG    | src.ssn:step:243 - loss=6.518104e-01, loss_new=0.9082575351204092, theta=1.00e-12
2026-04-13 15:26:30.743 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:30.743 | DEBUG    | src.ssn:step:243 - loss=6.518104e-01, loss_new=0.9082575351204092, theta=1.00e-12
2026-04-13 15:26:30.822 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:30.822 | DEBUG    | src.ssn:step:243 - loss=6.518104e-01, loss_new=0.9082575351204092, theta=1.00e-12
2026-04-13 15:26:31.736 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:31.737 | DEBUG    | src.ssn:step:243 - loss=2.843775e-01, loss_new=3.9055964958525036, theta=1.00e-12
2026-04-13 15:26:31.824 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:31.824 | DEBUG    | src.ssn:step:243 - loss=2.843775e-01, loss_new=3.9055964958525036, theta=1.00e-12
2026-04-13 15:26:31.910 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:31.910 | DEBUG    | src.ssn:step:243 - loss=2.843775e-01, loss_new=3.9055964958525036, theta=1.00e-12
2026-04-13 15:26:32.953 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:32.953 | DEBUG    | src.ssn:step:243 - loss=2.687790e-01, loss_new=12.172483901159948, theta=1.00e-12
2026-04-13 15:26:33.042 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:33.042 | DEBUG    | src.ssn:step:243 - loss=2.687790e-01, loss_new=12.172483901159948, theta=1.00e-12
2026-04-13 15:26:33.131 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:33.131 | DEBUG    | src.ssn:step:243 - loss=2.687790e-01, loss_new=12.172483901159948, theta=1.00e-12
2026-04-13 15:26:34.232 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:34.232 | DEBUG    | src.ssn:step:243 - loss=2.527385e-01, loss_new=12.481338587259575, theta=1.00e-12
2026-04-13 15:26:34.329 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:34.329 | DEBUG    | src.ssn:step:243 - loss=2.527385e-01, loss_new=12.481338587259575, theta=1.00e-12
2026-04-13 15:26:34.425 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:34.425 | DEBUG    | src.ssn:step:243 - loss=2.527385e-01, loss_new=12.481338587259575, theta=1.00e-12
2026-04-13 15:26:35.646 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:35.646 | DEBUG    | src.ssn:step:243 - loss=2.401012e-01, loss_new=11.716551526687011, theta=1.00e-12
2026-04-13 15:26:35.747 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:35.747 | DEBUG    | src.ssn:step:243 - loss=2.401012e-01, loss_new=11.716551526687011, theta=1.00e-12
2026-04-13 15:26:35.850 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:35.850 | DEBUG    | src.ssn:step:243 - loss=2.401012e-01, loss_new=11.716551526687011, theta=1.00e-12
2026-04-13 15:26:37.148 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:37.148 | DEBUG    | src.ssn:step:243 - loss=2.289401e-01, loss_new=27.867669092771372, theta=1.00e-12
2026-04-13 15:26:37.250 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:37.250 | DEBUG    | src.ssn:step:243 - loss=2.289401e-01, loss_new=27.867669092771372, theta=1.00e-12
2026-04-13 15:26:37.351 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:37.351 | DEBUG    | src.ssn:step:243 - loss=2.289401e-01, loss_new=27.867669092771372, theta=1.00e-12
2026-04-13 15:26:38.739 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:38.739 | DEBUG    | src.ssn:step:243 - loss=2.229470e-01, loss_new=67.88363591656457, theta=1.00e-12
2026-04-13 15:26:38.851 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:38.851 | DEBUG    | src.ssn:step:243 - loss=2.229470e-01, loss_new=67.88363591656457, theta=1.00e-12
2026-04-13 15:26:38.960 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:38.961 | DEBUG    | src.ssn:step:243 - loss=2.229470e-01, loss_new=67.88363591656457, theta=1.00e-12
2026-04-13 15:26:40.282 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:40.282 | DEBUG    | src.ssn:step:243 - loss=2.174461e-01, loss_new=77.19146233016417, theta=1.00e-12
2026-04-13 15:26:40.397 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:40.397 | DEBUG    | src.ssn:step:243 - loss=2.174461e-01, loss_new=77.19146233016417, theta=1.00e-12
2026-04-13 15:26:40.512 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:40.512 | DEBUG    | src.ssn:step:243 - loss=2.174461e-01, loss_new=77.19146233016417, theta=1.00e-12
2026-04-13 15:26:41.732 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:41.732 | DEBUG    | src.ssn:step:243 - loss=2.096672e-01, loss_new=88.8750459126604, theta=1.00e-12
2026-04-13 15:26:41.848 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:41.848 | DEBUG    | src.ssn:step:243 - loss=2.096672e-01, loss_new=88.8750459126604, theta=1.00e-12
2026-04-13 15:26:41.963 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:41.964 | DEBUG    | src.ssn:step:243 - loss=2.096672e-01, loss_new=88.8750459126604, theta=1.00e-12

alpha=1e-05, gamma=0: N=33, err_l2=2.30e-01

2026-04-13 15:26:44.986 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:44.987 | DEBUG    | src.ssn:step:243 - loss=6.517838e-01, loss_new=0.9080584159626669, theta=1.00e-12
2026-04-13 15:26:45.070 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:45.070 | DEBUG    | src.ssn:step:243 - loss=6.517838e-01, loss_new=0.9080584159626669, theta=1.00e-12
2026-04-13 15:26:45.154 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:45.154 | DEBUG    | src.ssn:step:243 - loss=6.517838e-01, loss_new=0.9080584159626669, theta=1.00e-12
2026-04-13 15:26:46.062 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:46.062 | DEBUG    | src.ssn:step:243 - loss=2.843501e-01, loss_new=3.905096862615995, theta=1.00e-12
2026-04-13 15:26:46.153 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:46.153 | DEBUG    | src.ssn:step:243 - loss=2.843501e-01, loss_new=3.905096862615995, theta=1.00e-12
2026-04-13 15:26:46.244 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:46.245 | DEBUG    | src.ssn:step:243 - loss=2.843501e-01, loss_new=3.905096862615995, theta=1.00e-12
2026-04-13 15:26:47.305 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:47.305 | DEBUG    | src.ssn:step:243 - loss=2.687453e-01, loss_new=12.171192593230137, theta=1.00e-12
2026-04-13 15:26:47.400 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:47.400 | DEBUG    | src.ssn:step:243 - loss=2.687453e-01, loss_new=12.171192593230137, theta=1.00e-12
2026-04-13 15:26:47.494 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:47.494 | DEBUG    | src.ssn:step:243 - loss=2.687453e-01, loss_new=12.171192593230137, theta=1.00e-12
2026-04-13 15:26:48.614 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:48.615 | DEBUG    | src.ssn:step:243 - loss=2.527061e-01, loss_new=12.479521460267042, theta=1.00e-12
2026-04-13 15:26:48.720 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:48.720 | DEBUG    | src.ssn:step:243 - loss=2.527061e-01, loss_new=12.479521460267042, theta=1.00e-12
2026-04-13 15:26:48.822 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:48.823 | DEBUG    | src.ssn:step:243 - loss=2.527061e-01, loss_new=12.479521460267042, theta=1.00e-12
2026-04-13 15:26:50.000 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:50.000 | DEBUG    | src.ssn:step:243 - loss=2.400777e-01, loss_new=11.71586204000765, theta=1.00e-12
2026-04-13 15:26:50.105 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:50.105 | DEBUG    | src.ssn:step:243 - loss=2.400777e-01, loss_new=11.71586204000765, theta=1.00e-12
2026-04-13 15:26:50.210 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:50.211 | DEBUG    | src.ssn:step:243 - loss=2.400777e-01, loss_new=11.71586204000765, theta=1.00e-12
2026-04-13 15:26:51.539 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:51.539 | DEBUG    | src.ssn:step:243 - loss=2.289175e-01, loss_new=27.86073216058147, theta=1.00e-12
2026-04-13 15:26:51.645 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:51.645 | DEBUG    | src.ssn:step:243 - loss=2.289175e-01, loss_new=27.86073216058147, theta=1.00e-12
2026-04-13 15:26:51.751 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:51.751 | DEBUG    | src.ssn:step:243 - loss=2.289175e-01, loss_new=27.86073216058147, theta=1.00e-12
2026-04-13 15:26:53.122 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:53.122 | DEBUG    | src.ssn:step:243 - loss=2.229267e-01, loss_new=67.88169166204636, theta=1.00e-12
2026-04-13 15:26:53.238 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:53.239 | DEBUG    | src.ssn:step:243 - loss=2.229267e-01, loss_new=67.88169166204636, theta=1.00e-12
2026-04-13 15:26:53.353 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:53.353 | DEBUG    | src.ssn:step:243 - loss=2.229267e-01, loss_new=67.88169166204636, theta=1.00e-12
2026-04-13 15:26:54.682 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:54.682 | DEBUG    | src.ssn:step:243 - loss=2.173729e-01, loss_new=74.10990435657436, theta=1.00e-12
2026-04-13 15:26:54.802 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:54.803 | DEBUG    | src.ssn:step:243 - loss=2.173729e-01, loss_new=74.10990435657436, theta=1.00e-12
2026-04-13 15:26:54.922 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:54.923 | DEBUG    | src.ssn:step:243 - loss=2.173729e-01, loss_new=74.10990435657436, theta=1.00e-12
2026-04-13 15:26:56.126 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:56.126 | DEBUG    | src.ssn:step:243 - loss=2.124336e-01, loss_new=68.36288481910549, theta=1.00e-12
2026-04-13 15:26:56.310 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:56.310 | DEBUG    | src.ssn:step:243 - loss=2.124336e-01, loss_new=68.36288481910549, theta=1.00e-12
2026-04-13 15:26:56.479 | DEBUG    | src.ssn:step:242 - Line search failed after 500 iterations
2026-04-13 15:26:56.479 | DEBUG    | src.ssn:step:243 - loss=2.124336e-01, loss_new=68.36288481910549, theta=1.00e-12

alpha=1e-05, gamma=5: N=33, err_l2=2.31e-01

In [15]:
rows = []
for a in alphas:
    row = {'alpha': f"{a:.0e}"}
    for g in gammas_alpha:
        r = results_alpha_v2[(a, g)]
        bi = r['best_iteration']
        row[f'N (gamma={g})'] = r['best_neurons']
        row[f'||N-f|| (gamma={g})'] = f"{r['err_l2_train'][bi]:.2e}"
    rows.append(row)

alpha_df = pd.DataFrame(rows).set_index('alpha')
display(alpha_df)

       N (gamma=0) ||N-f|| (gamma=0)  N (gamma=5) ||N-f|| (gamma=5)
alpha
1e-02           27          2.34e-01           27          2.34e-01
1e-03           28          2.34e-01           28          2.34e-01
1e-04           28          2.34e-01           28          2.34e-01
1e-05           33          2.30e-01           33          2.31e-01